import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  // Translations map
  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'AI Ration Mitra',
      'citizen_login': 'Citizen Login',
      'fps_login': 'FPS Dealer Login',
      'admin_login': 'Admin Login',
      'secure_authentication': 'Secure Authentication',
      'welcome_back': 'Welcome Back!',
      'access_ration': 'Access your ration entitlements',
      'aadhaar': 'Aadhaar',
      'mobile': 'Mobile',
      'enter_aadhaar': 'Enter Aadhaar Number',
      'enter_mobile': 'Enter Mobile Number',
      'password': 'Password',
      'enter_password': 'Enter Password',
      'login': 'Login',
      'register': 'Register',
      'dont_have_account': "Don't have an account?",
      'register_now': 'Register Now',
      'home': 'Home',
      'entitlements': 'Entitlements',
      'fps_locator': 'FPS Locator',
      'profile': 'Profile',
      'settings': 'Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications',
      'receive_updates': 'Receive updates',
      'account': 'Account',
      'edit_profile': 'Edit Profile',
      'logout': 'Logout',
      'appearance': 'Appearance',
      'switch_theme': 'Switch theme',
      'my_grievances': 'My Grievances',
      'book_slot': 'Book Slot',
      'slot_booking': 'Slot Booking',
      'select_convenient_time':
          'Select a convenient time to collect your ration',
      'choose_date': 'Choose Date',
      'choose_time': 'Choose Time',
      'confirm_booking': 'Confirm Booking',
      'grievance': 'Grievance',
      'submit': 'Submit',
      'grievances': 'Grievances',
      'my_entitlements': 'My Entitlements',
      'view_entitlements': 'View your entitlements',
      'find_fps': 'Find FPS',
      'search_fps_depot': 'Search FPS Depot nearby',
      'citizen_portal': 'Citizen Portal',
      'quick_actions': 'Quick Actions',
      'upcoming_distributions': 'Upcoming Distributions',
      'no_distributions': 'No upcoming distributions',
      'entitlement': 'Entitlement',
      'quantity': 'Quantity',
      'status': 'Status',
      'pending': 'Pending',
      'completed': 'Completed',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'name': 'Name',
      'email': 'Email',
      'address': 'Address',
      'mobile_number': 'Mobile Number',
      'fps_name': 'FPS Name',
      'fps_owner': 'FPS Owner Name',
      'fps_location': 'FPS Location',
      'directions': 'Directions',
      'call': 'Call',
      'shops_found': 'FPS Shops Found',
      'save_changes': 'Save Changes',
      'update_profile': 'Update Profile',
      'view_profile': 'View Profile',
      'distributor': 'Distributor',
      'beneficiary': 'Beneficiary',
      'submit_grievance': 'Submit a Grievance',
      'grievance_details': 'Grievance Details',
      'category': 'Category',
      'title': 'Title',
      'description': 'Description',
      'attachment': 'Attachment',
      'remarks': 'Remarks',
      'submitted': 'Submitted',
      'created_at': 'Created At',
      'in_progress': 'In Progress',
      'resolved': 'Resolved',
      'rejected': 'Rejected',
      'required_field': 'This field is required',
      'profile_updated': 'Profile updated successfully',
      'select_portal': 'Select Portal',
      'choose_role_continue': 'Choose your role and continue securely',
      'digital_india_initiative': 'Digital India Initiative',
      'hero_line_1': 'Smart, transparent and secure Public Distribution System',
      'hero_line_2': 'Fast access to ration services for every family',
      'hero_line_3': 'One platform for citizens, FPS dealers and admins',
      'fps_dealer': 'FPS Dealer',
      'admin_portal': 'Admin Portal',
      'citizen_portal_select': 'Citizen Portal',
      'fps_owner_panel': 'Ration Shop Owner Panel',
      'shop_active': 'Shop Active',
      'eligible_today': 'Eligible Today',
      'distributed_today': 'Distributed Today',
      'low_stock_items': 'Low Stock Items',
      'pending_requisitions': 'Pending Requisitions',
      'quick_operations': 'Quick Operations',
      'scan_beneficiary': 'Scan Beneficiary',
      'manage_stock': 'Manage Stock',
      'distribution_queue': 'Distribution Queue',
      'plan_distribution': 'Plan Distribution',
      'beneficiary_registry': 'Beneficiary Registry',
      'dealer_profile': 'Dealer Profile',
      'low_stock_alerts': 'Low Stock Alerts',
      'all_stock_healthy': 'All stock levels are healthy.',
      'manage': 'Manage',
      'raise_request': 'Raise Request',
      'fps_shops': 'FPS Shops',
      'beneficiaries': 'Beneficiaries',
      'monthly_distribution': 'Monthly Dist.',
      'system_overview': 'System Overview',
      'new_update_available': 'New Update Available',
      'map_unavailable': 'Map is unavailable on this device.',
      'list_only_mode': 'Showing list view only.',
      'fps_locator_title': 'FPS Locator',
      'shop_active_dashboard': 'Daily operational dashboard for distribution and stock',
      'secure_auth_uidai': 'Secure authentication via UIDAI',
    },
    'hi': {
      'app_title': 'एआई राशन मित्र',
      'citizen_login': 'नागरिक लॉगिन',
      'fps_login': 'एफपीएस डीलर लॉगिन',
      'admin_login': 'प्रशासक लॉगिन',
      'secure_authentication': 'सुरक्षित प्रमाणीकरण',
      'welcome_back': 'स्वागत है!',
      'access_ration': 'अपने राशन पात्रता तक पहुंचें',
      'aadhaar': 'आधार',
      'mobile': 'मोबाइल',
      'enter_aadhaar': 'आधार नंबर दर्ज करें',
      'enter_mobile': 'मोबाइल नंबर दर्ज करें',
      'password': 'पासवर्ड',
      'enter_password': 'पासवर्ड दर्ज करें',
      'login': 'लॉगिन करें',
      'register': 'पंजीकरण करें',
      'dont_have_account': 'खाता नहीं है?',
      'register_now': 'अभी पंजीकरण करें',
      'home': 'होम',
      'entitlements': 'पात्रताएं',
      'fps_locator': 'एफपीएस लोकेटर',
      'profile': 'प्रोफाइल',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'dark_mode': 'डार्क मोड',
      'notifications': 'सूचनाएं',
      'enable_notifications': 'सूचनाओं को सक्षम करें',
      'receive_updates': 'अपडेट प्राप्त करें',
      'account': 'खाता',
      'edit_profile': 'प्रोफाइल संपादित करें',
      'logout': 'लॉगआउट',
      'appearance': 'उपस्थिति',
      'switch_theme': 'थीम स्विच करें',
      'my_grievances': 'मेरी शिकायतें',
      'book_slot': 'स्लॉट बुक करें',
      'slot_booking': 'स्लॉट बुकिंग',
      'select_convenient_time':
          'अपने राशन एकत्र करने के लिए सुविधाजनक समय चुनें',
      'choose_date': 'तारीख चुनें',
      'choose_time': 'समय चुनें',
      'confirm_booking': 'बुकिंग की पुष्टि करें',
      'grievance': 'शिकायत',
      'submit': 'जमा करें',
      'grievances': 'शिकायतें',
      'my_entitlements': 'मेरी पात्रताएं',
      'view_entitlements': 'अपनी पात्रताएं देखें',
      'find_fps': 'एफपीएस खोजें',
      'search_fps_depot': 'पास के एफपीएस डिपो खोजें',
      'citizen_portal': 'नागरिक पोर्टल',
      'quick_actions': 'त्वरित कार्य',
      'upcoming_distributions': 'आने वाले वितरण',
      'no_distributions': 'कोई आने वाला वितरण नहीं',
      'entitlement': 'पात्रता',
      'quantity': 'मात्रा',
      'status': 'स्थिति',
      'pending': 'लंबित',
      'completed': 'पूर्ण',
      'confirm': 'पुष्टि',
      'cancel': 'रद्द करें',
      'loading': 'लोड हो रहा है...',
      'error': 'त्रुटि',
      'success': 'सफल',
      'name': 'नाम',
      'email': 'ईमेल',
      'address': 'पता',
      'mobile_number': 'मोबाइल नंबर',
      'fps_name': 'एफपीएस नाम',
      'fps_owner': 'एफपीएस मालिक का नाम',
      'fps_location': 'एफपीएस स्थान',
      'directions': 'दिशाएं',
      'call': 'कॉल करें',
      'shops_found': 'एफपीएस दुकानें मिलीं',
      'save_changes': 'परिवर्तन सहेजें',
      'update_profile': 'प्रोफाइल अपडेट करें',
      'view_profile': 'प्रोफाइल देखें',
      'distributor': 'वितरक',
      'beneficiary': 'लाभार्थी',
      'submit_grievance': 'एक शिकायत जमा करें',
      'grievance_details': 'शिकायत विवरण',
      'category': 'श्रेणी',
      'title': 'शीर्षक',
      'description': 'विवरण',
      'attachment': 'अटैचमेंट',
      'remarks': 'टिप्पणियां',
      'submitted': 'जमा किया गया',
      'created_at': 'बनाया गया',
      'in_progress': 'प्रगति में',
      'resolved': 'हल हो गया',
      'rejected': 'अस्वीकृत',
      'required_field': 'यह फील्ड आवश्यक है',
      'profile_updated': 'प्रोफाइल सफलतापूर्वक अपडेट हुआ',
      'select_portal': 'पोर्टल चुनें',
      'choose_role_continue': 'अपनी भूमिका चुनें और सुरक्षित रूप से आगे बढ़ें',
      'digital_india_initiative': 'डिजिटल इंडिया पहल',
      'hero_line_1': 'स्मार्ट, पारदर्शी और सुरक्षित सार्वजनिक वितरण प्रणाली',
      'hero_line_2': 'हर परिवार के लिए राशन सेवाओं तक तेज़ पहुंच',
      'hero_line_3': 'नागरिकों, एफपीएस डीलरों और प्रशासकों के लिए एक प्लेटफ़ॉर्म',
      'fps_dealer': 'एफपीएस डीलर',
      'admin_portal': 'प्रशासक पोर्टल',
      'citizen_portal_select': 'नागरिक पोर्टल',
      'fps_owner_panel': 'राशन दुकान मालिक पैनल',
      'shop_active': 'दुकान सक्रिय',
      'eligible_today': 'आज पात्र',
      'distributed_today': 'आज वितरित',
      'low_stock_items': 'कम स्टॉक आइटम',
      'pending_requisitions': 'लंबित मांग',
      'quick_operations': 'त्वरित संचालन',
      'scan_beneficiary': 'लाभार्थी स्कैन करें',
      'manage_stock': 'स्टॉक प्रबंधन',
      'distribution_queue': 'वितरण कतार',
      'plan_distribution': 'वितरण योजना',
      'beneficiary_registry': 'लाभार्थी रजिस्ट्रि',
      'dealer_profile': 'डीलर प्रोफाइल',
      'low_stock_alerts': 'कम स्टॉक अलर्ट',
      'all_stock_healthy': 'सभी स्टॉक स्तर स्वस्थ हैं।',
      'manage': 'प्रबंधित करें',
      'raise_request': 'अनुरोध भेजें',
      'fps_shops': 'एफपीएस दुकानें',
      'beneficiaries': 'लाभार्थी',
      'monthly_distribution': 'मासिक वितरण',
      'system_overview': 'सिस्टम अवलोकन',
      'new_update_available': 'नया अपडेट उपलब्ध',
      'map_unavailable': 'इस डिवाइस पर मैप उपलब्ध नहीं है।',
      'list_only_mode': 'केवल सूची दृश्य दिखाया जा रहा है।',
      'fps_locator_title': 'एफपीएस लोकेटर',
      'shop_active_dashboard':
          'वितरण और स्टॉक के लिए दैनिक संचालन डैशबोर्ड',
      'secure_auth_uidai': 'यूआईडीएआई के माध्यम से सुरक्षित प्रमाणीकरण',
    },
    'mr': {
      'app_title': 'एआই राशन मित्र',
      'citizen_login': 'नागरिक लॉगिन',
      'fps_login': 'एफपीएस डीलर लॉगिन',
      'admin_login': 'प्रशासक लॉगिन',
      'secure_authentication': 'सुरक्षित प्रमाणीकरण',
      'welcome_back': 'स्वागत आहे!',
      'access_ration': 'आपल्या राशन हक्कांमध्ये प्रवेश करा',
      'aadhaar': 'आधार',
      'mobile': 'मोबाइल',
      'enter_aadhaar': 'आधार क्रमांक प्रविष्ट करा',
      'enter_mobile': 'मोबाइल क्रमांक प्रविष्ट करा',
      'password': 'पासवर्ड',
      'enter_password': 'पासवर्ड प्रविष्ट करा',
      'login': 'लॉगिन करा',
      'register': 'नोंदणी करा',
      'dont_have_account': 'खाता नाही?',
      'register_now': 'आता नोंदणी करा',
      'home': 'होम',
      'entitlements': 'हक्क',
      'fps_locator': 'एफपीएस लोकेटर',
      'profile': 'प्रोफाइल',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'select_language': 'भाषा निवडा',
      'dark_mode': 'डार्क मोड',
      'notifications': 'सूचना',
      'enable_notifications': 'सूचना सक्षम करा',
      'receive_updates': 'अपडेट प्राप्त करा',
      'account': 'खाता',
      'edit_profile': 'प्रोफाइल संपादित करा',
      'logout': 'लॉगआउट',
      'appearance': 'दिसावट',
      'switch_theme': 'थीम बदला',
      'my_grievances': 'माझ्या तक्रारी',
      'book_slot': 'स्लॉट बुक करा',
      'slot_booking': 'स्लॉट बुकिंग',
      'select_convenient_time':
          'आपल्या राशन गोळा करण्यासाठी सुविधाजनक वेळ निवडा',
      'choose_date': 'तारीख निवडा',
      'choose_time': 'वेळ निवडा',
      'confirm_booking': 'बुकिंग पुष्टी करा',
      'grievance': 'तक्रार',
      'submit': 'सबमिट करा',
      'grievances': 'तक्रारी',
      'my_entitlements': 'माझ्या हक्क',
      'view_entitlements': 'आपल्या हक्क पहा',
      'find_fps': 'एफपीएस शोधा',
      'search_fps_depot': 'जवळपास एफपीएस डिपो शोधा',
      'citizen_portal': 'नागरिक पोर्टल',
      'quick_actions': 'द्रुत क्रिया',
      'upcoming_distributions': 'आगामी वितरण',
      'no_distributions': 'कोई आगामी वितरण नहीं',
      'entitlement': 'हक्क',
      'quantity': 'प्रमाण',
      'status': 'स्थिति',
      'pending': 'प्रलंबित',
      'completed': 'पूर्ण',
      'confirm': 'पुष्टी करा',
      'cancel': 'रद्द करा',
      'loading': 'लोड होत आहे...',
      'error': 'त्रुटी',
      'success': 'यश',
      'name': 'नाव',
      'email': 'ईमेल',
      'address': 'पता',
      'mobile_number': 'मोबाइल क्रमांक',
      'fps_name': 'एफपीएस नाव',
      'fps_owner': 'एफपीएस मालकाचे नाव',
      'fps_location': 'एफपीएस स्थान',
      'directions': 'दिशानिर्देश',
      'call': 'कॉल करा',
      'shops_found': 'एफपीएस दुकानें सापडली',
      'save_changes': 'बदल सेव करा',
      'update_profile': 'प्रोफाइल अपडेट करा',
      'view_profile': 'प्रोफाइल पहा',
      'distributor': 'वितरण करणारा',
      'beneficiary': 'लाभार्थी',
      'submit_grievance': 'एक तक्रार सबमिट करा',
      'grievance_details': 'तक्रार तपशील',
      'category': 'श्रेणी',
      'title': 'शीर्षक',
      'description': 'वर्णन',
      'attachment': 'संलग्नक',
      'remarks': 'टिप्पण्या',
      'submitted': 'सबमिट केले',
      'created_at': 'बनविले',
      'in_progress': 'प्रगतीत',
      'resolved': 'सोडवले',
      'rejected': 'नाकारले',
      'required_field': 'हे क्षेत्र आवश्यक आहे',
      'profile_updated': 'प्रोफाइल यशस्वीरित्या अपडेट झाले',
      'select_portal': 'पोर्टल निवडा',
      'choose_role_continue': 'आपली भूमिका निवडा आणि सुरक्षितपणे पुढे जा',
      'digital_india_initiative': 'डिजिटल इंडिया उपक्रम',
      'hero_line_1': 'स्मार्ट, पारदर्शक आणि सुरक्षित सार्वजनिक वितरण प्रणाली',
      'hero_line_2': 'प्रत्येक कुटुंबासाठी राशन सेवांना जलद प्रवेश',
      'hero_line_3': 'नागरिक, एफपीएस डीलर आणि प्रशासकांसाठी एक व्यासपीठ',
      'fps_dealer': 'एफपीएस डीलर',
      'admin_portal': 'प्रशासक पोर्टल',
      'citizen_portal_select': 'नागरिक पोर्टल',
      'fps_owner_panel': 'राशन दुकान मालक पॅनेल',
      'shop_active': 'दुकान सक्रिय',
      'eligible_today': 'आज पात्र',
      'distributed_today': 'आज वितरित',
      'low_stock_items': 'कमी स्टॉक आयटम',
      'pending_requisitions': 'प्रलंबित मागण्या',
      'quick_operations': 'जलद ऑपरेशन्स',
      'scan_beneficiary': 'लाभार्थी स्कॅन करा',
      'manage_stock': 'स्टॉक व्यवस्थापन',
      'distribution_queue': 'वितरण रांग',
      'plan_distribution': 'वितरण नियोजन',
      'beneficiary_registry': 'लाभार्थी नोंदणी',
      'dealer_profile': 'डीलर प्रोफाइल',
      'low_stock_alerts': 'कमी स्टॉक अलर्ट',
      'all_stock_healthy': 'सर्व स्टॉक पातळी चांगल्या आहेत.',
      'manage': 'व्यवस्थापित करा',
      'raise_request': 'विनंती पाठवा',
      'fps_shops': 'एफपीएस दुकाने',
      'beneficiaries': 'लाभार्थी',
      'monthly_distribution': 'मासिक वितरण',
      'system_overview': 'सिस्टम आढावा',
      'new_update_available': 'नवीन अपडेट उपलब्ध',
      'map_unavailable': 'या डिव्हाइसवर नकाशा उपलब्ध नाही.',
      'list_only_mode': 'फक्त सूची दृश्य दाखवत आहे.',
      'fps_locator_title': 'एफपीएस लोकेटर',
      'shop_active_dashboard':
          'वितरण आणि स्टॉकसाठी दैनंदिन ऑपरेशनल डॅशबोर्ड',
      'secure_auth_uidai': 'यूआयडीएआय द्वारे सुरक्षित प्रमाणीकरण',
    },
  };

  String translate(String key) {
    final langCode = locale.languageCode;
    return _translations[langCode]?[key] ?? _translations['en']?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi', 'mr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
